repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
      args: [--maxkb=750]
    - id: name-tests-test
      args: ['--django']
    - id: detect-private-key
    - id: check-yaml
    - id: check-json
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt
        - asr/requirements.txt
        - hotword/requirements.txt
        - respeaker/requirements.txt

# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.11.1
#     hooks:
#     -   id: pyupgrade

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
    - id: ruff # linter
      language_version: python3
    - id: ruff-format # formatter
      args: [ --check ]
      language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    - id: isort
      language_version: python3
