repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
      args: [--maxkb=750]
    - id: name-tests-test
      args: ['--django']
    - id: detect-private-key
    - id: check-yaml
    - id: check-json
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt
        - asr/requirements.txt
        - hotword/requirements.txt
        - respeaker/requirements.txt

-   repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    - id: black
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    - id: flake8
      exclude: ^docs/|^rasa/nlu/external/

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3

-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
    -   id: pyupgrade

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.660
#     hooks:
#     -   id: mypy
#         language_version: python3
