PROJECT_ENV_VAR = "PROJECT"
DEFAULT_LOG_DIR = "logs"

AUDIO_DEVICE_ID_ENV_VAR = "AUDIO_DEVICE_ID"

# Rabbit MQ env. vars
Q_EXCHANGE_ENV_VAR = "Q_EXCHANGE"
RABBITMQ_HOST_ENV_VAR = "RABBITMQ_HOST"
RABBITMQ_PORT_ENV_VAR = "RABBITMQ_PORT"
DEFAULT_RABBITMQ_HOST = "localhost"
DEFAULT_RABBITMQ_PORT = 5672
DEFAULT_EXCHANGE = "fiona"

DEFAULT_HOTWORD_ASR_TOPIC = "hotword.detected"
DEFAULT_ASR_NLU_TOPIC = "asr.complete"
DEFAULT_NLU_ACTION_TOPIC = "nlu.complete"

# Hotword detection
HOTWORD_MODEL_ENV_VAR = "HOTWORD_MODEL_PB_PATH"
PRECISE_ENGINE_ENV_VAR = "PRECISE_ENGINE_BIN_PATH"

# ASR
