DEFAULT_LOG_DIR = "logs"


PROJECT_ENV_VAR = "PROJECT"
Q_EXCHANGE_ENV_VAR = "Q_EXCHANGE"
HOTWORD_MODEL_ENV_VAR = "HOTWORD_MODEL"

AUDIO_DEVICE_ID_ENV_VAR = "AUDIO_DEVICE_ID"
ASR_MODEL_ENV_VAR = "ASR_MODEL"
ASR_SCORER_ENV_VAR = "ASR_SCORER"
