PROJECT_ENV_VAR = "PROJECT_NAME"
DEFAULT_LOG_DIR = "logs"

# Audio device configuration
AUDIO_DEVICE_ID_ENV_VAR = "AUDIO_DEVICE_ID"
AUDIO_SAMPLE_RATE_ENV_VAR = "AUDIO_SAMPLE_RATE"
AUDIO_DEFAULT_SAMPLE_RATE = 16000

# [DEPRECATED] Rabbit MQ env. vars
Q_EXCHANGE_ENV_VAR = "Q_EXCHANGE"
RABBITMQ_HOST_ENV_VAR = "RABBITMQ_HOST"
RABBITMQ_PORT_ENV_VAR = "RABBITMQ_PORT"
DEFAULT_RABBITMQ_HOST = "localhost"
DEFAULT_RABBITMQ_PORT = 5672
DEFAULT_EXCHANGE = "fiona"

DEFAULT_HOTWORD_ASR_TOPIC = "hotword.detected"
DEFAULT_ASR_NLU_TOPIC = "asr.complete"
DEFAULT_NLU_ACTION_TOPIC = "nlu.complete"

# Hotword detection
HOTWORD_MODEL_ENV_VAR = "HOTWORD_MODEL_PB_PATH"
HOTWORD_MODEL_DEFAULT_PATH = "hotword/models/fiona/fiona.pb"
PRECISE_ENGINE_ENV_VAR = "PRECISE_ENGINE_BIN_PATH"
PRECISE_ENGINE_DEFAULT_BIN_PATH = "hotword/mycroft-precise/.venv/bin/precise-engine"

# ASR
ASR_SERVER_URI_ENV_VAR = "ASR_SERVER_URI"
ASR_SERVER_DEFAULT_URI = "ws://localhost:2700"

# NLU
NLU_SERVER_DEFAULT_URI = "http://localhost:8000"
NLU_SERVER_URI_ENV_VAR = "NLU_SERVER_URI"
